version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-resilience4j
    volumes:
      - ./docker-prometheus-grafana/prometheus-desktop.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - net
    depends_on:
      - app
  grafana:
    image: grafana/grafana
    container_name: grafana-resilience4j
    env_file:
      - docker-prometheus-grafana/grafana.env
    ports:
      - "3000:3000"
    networks:
      - net
  app:
    image: spring-resilience4j-demo
    container_name: spring-resilience4j-demo
    ports:
      - "8082:8082"
    networks:
      - net
networks:
  net:
