version: '3'

services:
  telegraf:
    image: telegraf:1.17.2
    volumes:
      - ./docker-splunk/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./docker-splunk/logs/telegraf:/var/log
    ports:
      - "8125:8125/udp"
  splunk:
    image: splunk/splunk:8.1.2
    volumes:
      - ./docker-splunk/splunk-config.yml:/tmp/defaults/default.yml
      - ./docker-splunk/logs/splunk:/opt/splunk/var/log/splunk
      - ./docker-splunk/indexes.conf:/opt/splunk/etc/system/local/indexes.conf
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=splunkpwd1
    ports:
      - 8000:8000
      - 8088:8088
    depends_on:
      - telegraf
